version: "3"

services:
  isdb_cw-db:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    image: postgres
    volumes:
      - ${PERSISTENCE_VOLUME}
    ports:
      - "5432:5432"

volumes:
  db_data:
